.PHONY: run_server # Build and run Node server
run_server:
	npm install
	npm run build
	npm run server

.PHONY: fmt # Format Javascript code
fmt:
	npm install
	npm run format

.PHONY: check_fmt # Check Javascript code format
check_fmt:
	npm install
	npm run check-format
