runners:
  cpu-big:
    family: m6i.32xlarge
    image: ubuntu24-full-x64
    volume: 200gb
    spot: false
  cpu-small:
    family: m6i.4xlarge
    image: ubuntu24-full-x64
    volume: 200gb
    spot: false
