FROM rust:1.67 as builder

WORKDIR /usr/local/app
ADD . /usr/local/app
RUN make build_c_api

FROM debian:bullseye-slim
WORKDIR /usr/local/app/tfhe-rs/lib
COPY  --from=builder /usr/local/app/target/release/libtfhe.* /usr/local/app/tfhe-rs/lib/
COPY  --from=builder /usr/local/app/target/release/tfhe.h .
