FROM ubuntu:22.04

ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Replace default archive.ubuntu.com with fr mirror
# original archive showed performance issues and is farther away
RUN sed -i 's|^deb http://archive.ubuntu.com/ubuntu/|deb http://mirror.ubuntu.ikoula.com/|g' /etc/apt/sources.list && \
    sed -i 's|^deb http://security.ubuntu.com/ubuntu/|deb http://mirror.ubuntu.ikoula.com/|g' /etc/apt/sources.list

ENV CARGO_TARGET_DIR=/root/tfhe-rs-target

ARG RUST_TOOLCHAIN="stable"
ARG NODE_VERSION

WORKDIR /tfhe-wasm-tests

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    curl \
    git \
    python3 \
    python3-pip \
    python3-venv && \
    rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > install-rustup.sh && \
    chmod +x install-rustup.sh && \
    ./install-rustup.sh -y --default-toolchain "${RUST_TOOLCHAIN}" \
    -c rust-src -t wasm32-unknown-unknown && \
    . "$HOME/.cargo/env" && \
    cargo install wasm-pack && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh > install-node.sh && \
    chmod +x install-node.sh && \
    ./install-node.sh && \
    . "$HOME/.nvm/nvm.sh" && \
    bash -i -c 'nvm install ${NODE_VERSION} && nvm use ${NODE_VERSION}'

WORKDIR /tfhe-wasm-tests/tfhe-rs/
