name: Setup Cuda
description: Setup Cuda on Hyperstack instance

inputs:
  cuda-version:
    description: Version of Cuda to use
    required: true
  gcc-version:
    description: Version of GCC to use
    required: true

runs:
  using: "composite"
  env:
    CUDA_PATH: /usr/local/cuda-${{ inputs.cuda-version }}
    CMAKE_VERSION: 3.29.6
  steps:
    # Mandatory on hyperstack since a bootable volume is not re-usable yet.
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y checkinstall zlib1g-dev libssl-dev libclang-dev
        wget https://github.com/Kitware/CMake/releases/download/v${{ env.CMAKE_VERSION }}/cmake-${{ env.CMAKE_VERSION }}.tar.gz
        tar -zxvf cmake-${{ env.CMAKE_VERSION }}.tar.gz
        cd cmake-${{ env.CMAKE_VERSION }}
        ./bootstrap
        make -j"$(nproc)"
        sudo make install

    - name: Export CUDA variables
      run: |
        echo "CUDA_PATH=$CUDA_PATH" >> "${GITHUB_ENV}"
        echo "$CUDA_PATH/bin" >> "${GITHUB_PATH}"
        echo "LD_LIBRARY_PATH=$CUDA_PATH/lib:$LD_LIBRARY_PATH" >> "${GITHUB_ENV}"
        echo "CUDACXX=/usr/local/cuda-${{ inputs.cuda-version }}/bin/nvcc" >> "${GITHUB_ENV}"

    # Specify the correct host compilers
    - name: Export gcc and g++ variables
      run: |
        {
          echo "CC=/usr/bin/gcc-${{ inputs.gcc-version }}";
          echo "CXX=/usr/bin/g++-${{ inputs.gcc-version }}";
          echo "CUDAHOSTCXX=/usr/bin/g++-${{ inputs.gcc-version }}";
          echo "HOME=/home/ubuntu";
        } >> "${GITHUB_ENV}"

    - name: Check device is detected
      run: nvidia-smi