/* automatically generated by rust-bindgen 0.71.1 */

use crate::ffi;

unsafe extern "C" {
    pub fn cuda_get_device() -> u32;
}
unsafe extern "C" {
    pub fn cuda_set_device(gpu_index: u32);
}
unsafe extern "C" {
    pub fn cuda_create_event(gpu_index: u32) -> *mut ffi::c_void;
}
unsafe extern "C" {
    pub fn cuda_event_record(event: *mut ffi::c_void, stream: *mut ffi::c_void, gpu_index: u32);
}
unsafe extern "C" {
    pub fn cuda_stream_wait_event(
        stream: *mut ffi::c_void,
        event: *mut ffi::c_void,
        gpu_index: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_event_destroy(event: *mut ffi::c_void, gpu_index: u32);
}
unsafe extern "C" {
    pub fn cuda_create_stream(gpu_index: u32) -> *mut ffi::c_void;
}
unsafe extern "C" {
    pub fn cuda_destroy_stream(stream: *mut ffi::c_void, gpu_index: u32);
}
unsafe extern "C" {
    pub fn cuda_synchronize_stream(stream: *mut ffi::c_void, gpu_index: u32);
}
unsafe extern "C" {
    pub fn cuda_is_available() -> u32;
}
unsafe extern "C" {
    pub fn cuda_malloc(size: u64, gpu_index: u32) -> *mut ffi::c_void;
}
unsafe extern "C" {
    pub fn cuda_malloc_with_size_tracking_async(
        size: u64,
        stream: *mut ffi::c_void,
        gpu_index: u32,
        size_tracker: *mut u64,
        allocate_gpu_memory: bool,
    ) -> *mut ffi::c_void;
}
unsafe extern "C" {
    pub fn cuda_malloc_async(
        size: u64,
        stream: *mut ffi::c_void,
        gpu_index: u32,
    ) -> *mut ffi::c_void;
}
unsafe extern "C" {
    pub fn cuda_check_valid_malloc(size: u64, gpu_index: u32) -> bool;
}
unsafe extern "C" {
    pub fn cuda_device_total_memory(gpu_index: u32) -> u64;
}
unsafe extern "C" {
    pub fn cuda_memcpy_with_size_tracking_async_to_gpu(
        dest: *mut ffi::c_void,
        src: *const ffi::c_void,
        size: u64,
        stream: *mut ffi::c_void,
        gpu_index: u32,
        gpu_memory_allocated: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_memcpy_async_to_gpu(
        dest: *mut ffi::c_void,
        src: *const ffi::c_void,
        size: u64,
        stream: *mut ffi::c_void,
        gpu_index: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_memcpy_with_size_tracking_async_gpu_to_gpu(
        dest: *mut ffi::c_void,
        src: *const ffi::c_void,
        size: u64,
        stream: *mut ffi::c_void,
        gpu_index: u32,
        gpu_memory_allocated: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_memcpy_async_gpu_to_gpu(
        dest: *mut ffi::c_void,
        src: *const ffi::c_void,
        size: u64,
        stream: *mut ffi::c_void,
        gpu_index: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_memcpy_gpu_to_gpu(
        dest: *mut ffi::c_void,
        src: *const ffi::c_void,
        size: u64,
        gpu_index: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_memcpy_async_to_cpu(
        dest: *mut ffi::c_void,
        src: *const ffi::c_void,
        size: u64,
        stream: *mut ffi::c_void,
        gpu_index: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_memset_with_size_tracking_async(
        dest: *mut ffi::c_void,
        val: u64,
        size: u64,
        stream: *mut ffi::c_void,
        gpu_index: u32,
        gpu_memory_allocated: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_memset_async(
        dest: *mut ffi::c_void,
        val: u64,
        size: u64,
        stream: *mut ffi::c_void,
        gpu_index: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_get_number_of_gpus() -> ffi::c_int;
}
unsafe extern "C" {
    pub fn cuda_get_number_of_sms() -> ffi::c_int;
}
unsafe extern "C" {
    pub fn cuda_synchronize_device(gpu_index: u32);
}
unsafe extern "C" {
    pub fn cuda_drop(ptr: *mut ffi::c_void, gpu_index: u32);
}
unsafe extern "C" {
    pub fn cuda_drop_with_size_tracking_async(
        ptr: *mut ffi::c_void,
        stream: *mut ffi::c_void,
        gpu_index: u32,
        gpu_memory_allocated: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_drop_async(ptr: *mut ffi::c_void, stream: *mut ffi::c_void, gpu_index: u32);
}
