[package]
name = "param_dedup"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
syn = { version = "3.0.4", features = ["parsing", "full", "extra-traits"] }
semver = "1.0.26"
cargo_toml = "1.0"
walkdir = "2.5.0"
clap = { version = "=4.6.4", features = ["derive"] }
prettyplease = "0.3.0"
rayon = "1"
