/* automatically generated by rust-bindgen 0.71.1 */

use crate::ffi;

unsafe extern "C" {
    pub fn cuda_convert_lwe_ciphertext_vector_to_gpu_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        dest: *mut ffi::c_void,
        src: *const ffi::c_void,
        number_of_cts: u32,
        lwe_dimension: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_convert_lwe_ciphertext_vector_to_cpu_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        dest: *mut ffi::c_void,
        src: *const ffi::c_void,
        number_of_cts: u32,
        lwe_dimension: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_glwe_sample_extract_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut ffi::c_void,
        glwe_array_in: *const ffi::c_void,
        nth_array: *const u32,
        num_nths: u32,
        glwe_dimension: u32,
        polynomial_size: u32,
    );
}
pub const PBS_TYPE_MULTI_BIT: PBS_TYPE = 0;
pub const PBS_TYPE_CLASSICAL: PBS_TYPE = 1;
pub type PBS_TYPE = ffi::c_uint;
unsafe extern "C" {
    pub fn scratch_cuda_integer_compress_radix_ciphertext_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        compression_glwe_dimension: u32,
        compression_polynomial_size: u32,
        lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        num_radix_blocks: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        lwe_per_glwe: u32,
        storage_log_modulus: u32,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_decompress_radix_ciphertext_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        encryption_glwe_dimension: u32,
        encryption_polynomial_size: u32,
        compression_glwe_dimension: u32,
        compression_polynomial_size: u32,
        lwe_dimension: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        num_radix_blocks: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        storage_log_modulus: u32,
        body_count: u32,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_integer_compress_radix_ciphertext_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        glwe_array_out: *mut ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        fp_ksk: *const *mut ffi::c_void,
        num_nths: u32,
        mem_ptr: *mut i8,
    );
}
unsafe extern "C" {
    pub fn cuda_integer_decompress_radix_ciphertext_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array_out: *mut ffi::c_void,
        glwe_in: *const ffi::c_void,
        indexes_array: *const u32,
        indexes_array_size: u32,
        bsks: *const *mut ffi::c_void,
        mem_ptr: *mut i8,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_compress_radix_ciphertext_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_decompress_radix_ciphertext_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
pub const SHIFT_OR_ROTATE_TYPE_LEFT_SHIFT: SHIFT_OR_ROTATE_TYPE = 0;
pub const SHIFT_OR_ROTATE_TYPE_RIGHT_SHIFT: SHIFT_OR_ROTATE_TYPE = 1;
pub const SHIFT_OR_ROTATE_TYPE_LEFT_ROTATE: SHIFT_OR_ROTATE_TYPE = 2;
pub const SHIFT_OR_ROTATE_TYPE_RIGHT_ROTATE: SHIFT_OR_ROTATE_TYPE = 3;
pub type SHIFT_OR_ROTATE_TYPE = ffi::c_uint;
pub const BITOP_TYPE_BITAND: BITOP_TYPE = 0;
pub const BITOP_TYPE_BITOR: BITOP_TYPE = 1;
pub const BITOP_TYPE_BITXOR: BITOP_TYPE = 2;
pub const BITOP_TYPE_SCALAR_BITAND: BITOP_TYPE = 3;
pub const BITOP_TYPE_SCALAR_BITOR: BITOP_TYPE = 4;
pub const BITOP_TYPE_SCALAR_BITXOR: BITOP_TYPE = 5;
pub type BITOP_TYPE = ffi::c_uint;
pub const COMPARISON_TYPE_EQ: COMPARISON_TYPE = 0;
pub const COMPARISON_TYPE_NE: COMPARISON_TYPE = 1;
pub const COMPARISON_TYPE_GT: COMPARISON_TYPE = 2;
pub const COMPARISON_TYPE_GE: COMPARISON_TYPE = 3;
pub const COMPARISON_TYPE_LT: COMPARISON_TYPE = 4;
pub const COMPARISON_TYPE_LE: COMPARISON_TYPE = 5;
pub const COMPARISON_TYPE_MAX: COMPARISON_TYPE = 6;
pub const COMPARISON_TYPE_MIN: COMPARISON_TYPE = 7;
pub type COMPARISON_TYPE = ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CudaRadixCiphertextFFI {
    pub ptr: *mut ffi::c_void,
    pub degrees: *mut u64,
    pub noise_levels: *mut u64,
    pub num_radix_blocks: u32,
    pub lwe_dimension: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CudaRadixCiphertextFFI"][::std::mem::size_of::<CudaRadixCiphertextFFI>() - 32usize];
    ["Alignment of CudaRadixCiphertextFFI"]
        [::std::mem::align_of::<CudaRadixCiphertextFFI>() - 8usize];
    ["Offset of field: CudaRadixCiphertextFFI::ptr"]
        [::std::mem::offset_of!(CudaRadixCiphertextFFI, ptr) - 0usize];
    ["Offset of field: CudaRadixCiphertextFFI::degrees"]
        [::std::mem::offset_of!(CudaRadixCiphertextFFI, degrees) - 8usize];
    ["Offset of field: CudaRadixCiphertextFFI::noise_levels"]
        [::std::mem::offset_of!(CudaRadixCiphertextFFI, noise_levels) - 16usize];
    ["Offset of field: CudaRadixCiphertextFFI::num_radix_blocks"]
        [::std::mem::offset_of!(CudaRadixCiphertextFFI, num_radix_blocks) - 24usize];
    ["Offset of field: CudaRadixCiphertextFFI::lwe_dimension"]
        [::std::mem::offset_of!(CudaRadixCiphertextFFI, lwe_dimension) - 28usize];
};
unsafe extern "C" {
    pub fn scratch_cuda_apply_univariate_lut_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        input_lut: *const ffi::c_void,
        lwe_dimension: u32,
        glwe_dimension: u32,
        polynomial_size: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        input_lwe_ciphertext_count: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_apply_many_univariate_lut_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        input_lut: *const ffi::c_void,
        lwe_dimension: u32,
        glwe_dimension: u32,
        polynomial_size: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        num_radix_blocks: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        num_many_lut: u32,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_apply_univariate_lut_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        output_radix_lwe: *mut ffi::c_void,
        input_radix_lwe: *const ffi::c_void,
        mem_ptr: *mut i8,
        ksks: *const *mut ffi::c_void,
        bsks: *const *mut ffi::c_void,
        num_blocks: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_apply_univariate_lut_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_apply_bivariate_lut_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        input_lut: *const ffi::c_void,
        lwe_dimension: u32,
        glwe_dimension: u32,
        polynomial_size: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        input_lwe_ciphertext_count: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_apply_bivariate_lut_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        output_radix_lwe: *mut ffi::c_void,
        input_radix_lwe_1: *const ffi::c_void,
        input_radix_lwe_2: *const ffi::c_void,
        mem_ptr: *mut i8,
        ksks: *const *mut ffi::c_void,
        bsks: *const *mut ffi::c_void,
        num_blocks: u32,
        shift: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_apply_bivariate_lut_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn cuda_apply_many_univariate_lut_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        output_radix_lwe: *mut ffi::c_void,
        input_radix_lwe: *const ffi::c_void,
        mem_ptr: *mut i8,
        ksks: *const *mut ffi::c_void,
        bsks: *const *mut ffi::c_void,
        num_blocks: u32,
        num_luts: u32,
        lut_stride: u32,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_full_propagation_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        lwe_dimension: u32,
        glwe_dimension: u32,
        polynomial_size: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_full_propagation_64_inplace(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        input_blocks: *mut ffi::c_void,
        mem_ptr: *mut i8,
        ksks: *const *mut ffi::c_void,
        bsks: *const *mut ffi::c_void,
        num_blocks: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_full_propagation(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_mult_radix_ciphertext_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        is_boolean_left: bool,
        is_boolean_right: bool,
        message_modulus: u32,
        carry_modulus: u32,
        glwe_dimension: u32,
        lwe_dimension: u32,
        polynomial_size: u32,
        pbs_base_log: u32,
        pbs_level: u32,
        ks_base_log: u32,
        ks_level: u32,
        grouping_factor: u32,
        num_blocks: u32,
        pbs_type: PBS_TYPE,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_integer_mult_radix_ciphertext_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        radix_lwe_out: *mut ffi::c_void,
        radix_lwe_left: *const ffi::c_void,
        is_bool_left: bool,
        radix_lwe_right: *const ffi::c_void,
        is_bool_right: bool,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        mem_ptr: *mut i8,
        polynomial_size: u32,
        num_blocks: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_mult(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn cuda_negate_integer_radix_ciphertext_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        lwe_dimension: u32,
        lwe_ciphertext_count: u32,
        message_modulus: u32,
        carry_modulus: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_scalar_addition_integer_radix_ciphertext_64_inplace(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array: *mut ffi::c_void,
        scalar_input: *const ffi::c_void,
        lwe_dimension: u32,
        lwe_ciphertext_count: u32,
        message_modulus: u32,
        carry_modulus: u32,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_radix_logical_scalar_shift_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        big_lwe_dimension: u32,
        small_lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        num_blocks: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        shift_type: SHIFT_OR_ROTATE_TYPE,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_integer_radix_logical_scalar_shift_kb_64_inplace(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array: *mut ffi::c_void,
        shift: u32,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        num_blocks: u32,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_radix_arithmetic_scalar_shift_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        big_lwe_dimension: u32,
        small_lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        num_blocks: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        shift_type: SHIFT_OR_ROTATE_TYPE,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_integer_radix_arithmetic_scalar_shift_kb_64_inplace(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array: *mut ffi::c_void,
        shift: u32,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        num_blocks: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_radix_logical_scalar_shift(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_radix_arithmetic_scalar_shift(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_radix_shift_and_rotate_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        big_lwe_dimension: u32,
        small_lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        num_blocks: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        shift_type: SHIFT_OR_ROTATE_TYPE,
        is_signed: bool,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_integer_radix_shift_and_rotate_kb_64_inplace(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array: *mut ffi::c_void,
        lwe_shift: *const ffi::c_void,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        num_blocks: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_radix_shift_and_rotate(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_radix_comparison_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        big_lwe_dimension: u32,
        small_lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        lwe_ciphertext_count: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        op_type: COMPARISON_TYPE,
        is_signed: bool,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_comparison_integer_radix_ciphertext_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_array_1: *const ffi::c_void,
        lwe_array_2: *const ffi::c_void,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        lwe_ciphertext_count: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_scalar_comparison_integer_radix_ciphertext_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        scalar_blocks: *const ffi::c_void,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        lwe_ciphertext_count: u32,
        num_scalar_blocks: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_comparison(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_radix_bitop_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        big_lwe_dimension: u32,
        small_lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        lwe_ciphertext_count: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        op_type: BITOP_TYPE,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_bitop_integer_radix_ciphertext_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_array_1: *const ffi::c_void,
        lwe_array_2: *const ffi::c_void,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        lwe_ciphertext_count: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_scalar_bitop_integer_radix_ciphertext_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_array_input: *const ffi::c_void,
        clear_blocks: *const ffi::c_void,
        num_clear_blocks: u32,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        lwe_ciphertext_count: u32,
        op: BITOP_TYPE,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_bitop(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_radix_cmux_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        big_lwe_dimension: u32,
        small_lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        lwe_ciphertext_count: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_cmux_integer_radix_ciphertext_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array_out: *mut CudaRadixCiphertextFFI,
        lwe_condition: *const CudaRadixCiphertextFFI,
        lwe_array_true: *const CudaRadixCiphertextFFI,
        lwe_array_false: *const CudaRadixCiphertextFFI,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_radix_cmux(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_radix_scalar_rotate_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        big_lwe_dimension: u32,
        small_lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        num_blocks: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        shift_type: SHIFT_OR_ROTATE_TYPE,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_integer_radix_scalar_rotate_kb_64_inplace(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array: *mut ffi::c_void,
        n: u32,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        num_blocks: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_radix_scalar_rotate(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_propagate_single_carry_kb_64_inplace(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        big_lwe_dimension: u32,
        small_lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        num_blocks: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        requested_flag: u32,
        uses_carry: u32,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_add_and_propagate_single_carry_kb_64_inplace(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        big_lwe_dimension: u32,
        small_lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        num_blocks: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        requested_flag: u32,
        uses_carry: u32,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_propagate_single_carry_kb_64_inplace(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array: *mut ffi::c_void,
        carry_out: *mut ffi::c_void,
        carry_in: *const ffi::c_void,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        num_blocks: u32,
        requested_flag: u32,
        uses_carry: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_add_and_propagate_single_carry_kb_64_inplace(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lhs_array: *mut ffi::c_void,
        rhs_array: *const ffi::c_void,
        carry_out: *mut ffi::c_void,
        carry_in: *const ffi::c_void,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        num_blocks: u32,
        requested_flag: u32,
        uses_carry: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_propagate_single_carry(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_add_and_propagate_single_carry(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_overflowing_sub_kb_64_inplace(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        big_lwe_dimension: u32,
        small_lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        num_blocks: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        compute_overflow: u32,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_integer_overflowing_sub_kb_64_inplace(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lhs_array: *mut ffi::c_void,
        rhs_array: *const ffi::c_void,
        overflow_block: *mut ffi::c_void,
        input_borrow: *const ffi::c_void,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        num_blocks: u32,
        compute_overflow: u32,
        uses_input_borrow: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_overflowing_sub(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_radix_partial_sum_ciphertexts_vec_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        num_blocks_in_radix: u32,
        max_num_radix_in_vec: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_integer_radix_partial_sum_ciphertexts_vec_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        radix_lwe_out: *mut ffi::c_void,
        radix_lwe_vec: *mut ffi::c_void,
        num_radix_in_vec: u32,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        num_blocks_in_radix: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_radix_partial_sum_ciphertexts_vec(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_scalar_mul_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        num_blocks: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_scalar_multiplication_integer_radix_ciphertext_64_inplace(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array: *mut ffi::c_void,
        decomposed_scalar: *const u64,
        has_at_least_one_set: *const u64,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        lwe_dimension: u32,
        polynomial_size: u32,
        message_modulus: u32,
        num_blocks: u32,
        num_scalars: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_radix_scalar_mul(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_div_rem_radix_ciphertext_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        is_signed: bool,
        mem_ptr: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        big_lwe_dimension: u32,
        small_lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        num_blocks: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_integer_div_rem_radix_ciphertext_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        quotient: *mut ffi::c_void,
        remainder: *mut ffi::c_void,
        numerator: *const ffi::c_void,
        divisor: *const ffi::c_void,
        is_signed: bool,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        num_blocks_in_radix: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_div_rem(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_compute_prefix_sum_hillis_steele_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        input_lut: *const ffi::c_void,
        lwe_dimension: u32,
        glwe_dimension: u32,
        polynomial_size: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        num_radix_blocks: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_integer_compute_prefix_sum_hillis_steele_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        output_radix_lwe: *mut ffi::c_void,
        generates_or_propagates: *mut ffi::c_void,
        mem_ptr: *mut i8,
        ksks: *const *mut ffi::c_void,
        bsks: *const *mut ffi::c_void,
        num_blocks: u32,
        shift: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_compute_prefix_sum_hillis_steele_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn cuda_integer_reverse_blocks_64_inplace(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array: *mut ffi::c_void,
        num_blocks: u32,
        lwe_size: u32,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_abs_inplace_radix_ciphertext_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        is_signed: bool,
        glwe_dimension: u32,
        polynomial_size: u32,
        big_lwe_dimension: u32,
        small_lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        num_blocks: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_integer_abs_inplace_radix_ciphertext_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        ct: *mut CudaRadixCiphertextFFI,
        mem_ptr: *mut i8,
        is_signed: bool,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_abs_inplace(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_are_all_comparisons_block_true_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        big_lwe_dimension: u32,
        small_lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        num_radix_blocks: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_integer_are_all_comparisons_block_true_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        num_radix_blocks: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_are_all_comparisons_block_true(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_integer_is_at_least_one_comparisons_block_true_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        big_lwe_dimension: u32,
        small_lwe_dimension: u32,
        ks_level: u32,
        ks_base_log: u32,
        pbs_level: u32,
        pbs_base_log: u32,
        grouping_factor: u32,
        num_radix_blocks: u32,
        message_modulus: u32,
        carry_modulus: u32,
        pbs_type: PBS_TYPE,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_integer_is_at_least_one_comparisons_block_true_kb_64(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        mem_ptr: *mut i8,
        bsks: *const *mut ffi::c_void,
        ksks: *const *mut ffi::c_void,
        num_radix_blocks: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_integer_is_at_least_one_comparisons_block_true(
        streams: *const *mut ffi::c_void,
        gpu_indexes: *const u32,
        gpu_count: u32,
        mem_ptr_void: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn cuda_keyswitch_lwe_ciphertext_vector_32(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_output_indexes: *const ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        lwe_input_indexes: *const ffi::c_void,
        ksk: *const ffi::c_void,
        lwe_dimension_in: u32,
        lwe_dimension_out: u32,
        base_log: u32,
        level_count: u32,
        num_samples: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_keyswitch_lwe_ciphertext_vector_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_output_indexes: *const ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        lwe_input_indexes: *const ffi::c_void,
        ksk: *const ffi::c_void,
        lwe_dimension_in: u32,
        lwe_dimension_out: u32,
        base_log: u32,
        level_count: u32,
        num_samples: u32,
    );
}
unsafe extern "C" {
    pub fn scratch_packing_keyswitch_lwe_list_to_glwe_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        fp_ks_buffer: *mut *mut i8,
        lwe_dimension: u32,
        glwe_dimension: u32,
        polynomial_size: u32,
        num_lwes: u32,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_packing_keyswitch_lwe_list_to_glwe_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        glwe_array_out: *mut ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        fp_ksk_array: *const ffi::c_void,
        fp_ks_buffer: *mut i8,
        input_lwe_dimension: u32,
        output_glwe_dimension: u32,
        output_polynomial_size: u32,
        base_log: u32,
        level_count: u32,
        num_lwes: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_packing_keyswitch_lwe_list_to_glwe(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        fp_ks_buffer: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn cuda_negate_lwe_ciphertext_vector_32(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        input_lwe_dimension: u32,
        input_lwe_ciphertext_count: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_negate_lwe_ciphertext_vector_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        input_lwe_dimension: u32,
        input_lwe_ciphertext_count: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_add_lwe_ciphertext_vector_32(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut CudaRadixCiphertextFFI,
        lwe_array_in_1: *const CudaRadixCiphertextFFI,
        lwe_array_in_2: *const CudaRadixCiphertextFFI,
    );
}
unsafe extern "C" {
    pub fn cuda_add_lwe_ciphertext_vector_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut CudaRadixCiphertextFFI,
        lwe_array_in_1: *const CudaRadixCiphertextFFI,
        lwe_array_in_2: *const CudaRadixCiphertextFFI,
    );
}
unsafe extern "C" {
    pub fn cuda_add_lwe_ciphertext_vector_plaintext_vector_32(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        plaintext_array_in: *const ffi::c_void,
        input_lwe_dimension: u32,
        input_lwe_ciphertext_count: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_add_lwe_ciphertext_vector_plaintext_vector_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        plaintext_array_in: *const ffi::c_void,
        input_lwe_dimension: u32,
        input_lwe_ciphertext_count: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_mult_lwe_ciphertext_vector_cleartext_vector_32(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        cleartext_array_in: *const ffi::c_void,
        input_lwe_dimension: u32,
        input_lwe_ciphertext_count: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_mult_lwe_ciphertext_vector_cleartext_vector_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        cleartext_array_in: *const ffi::c_void,
        input_lwe_dimension: u32,
        input_lwe_ciphertext_count: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_add_lwe_ciphertext_vector_plaintext_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        plaintext_in: u64,
        input_lwe_dimension: u32,
        input_lwe_ciphertext_count: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_fourier_polynomial_mul(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        input1: *const ffi::c_void,
        input2: *const ffi::c_void,
        output: *mut ffi::c_void,
        polynomial_size: u32,
        total_polynomials: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_convert_lwe_programmable_bootstrap_key_32(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        dest: *mut ffi::c_void,
        src: *const ffi::c_void,
        input_lwe_dim: u32,
        glwe_dim: u32,
        level_count: u32,
        polynomial_size: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_convert_lwe_programmable_bootstrap_key_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        dest: *mut ffi::c_void,
        src: *const ffi::c_void,
        input_lwe_dim: u32,
        glwe_dim: u32,
        level_count: u32,
        polynomial_size: u32,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_programmable_bootstrap_amortized_32(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        pbs_buffer: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        input_lwe_ciphertext_count: u32,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_programmable_bootstrap_amortized_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        pbs_buffer: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        input_lwe_ciphertext_count: u32,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_programmable_bootstrap_amortized_lwe_ciphertext_vector_32(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_output_indexes: *const ffi::c_void,
        lut_vector: *const ffi::c_void,
        lut_vector_indexes: *const ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        lwe_input_indexes: *const ffi::c_void,
        bootstrapping_key: *const ffi::c_void,
        pbs_buffer: *mut i8,
        lwe_dimension: u32,
        glwe_dimension: u32,
        polynomial_size: u32,
        base_log: u32,
        level_count: u32,
        num_samples: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_programmable_bootstrap_amortized_lwe_ciphertext_vector_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_output_indexes: *const ffi::c_void,
        lut_vector: *const ffi::c_void,
        lut_vector_indexes: *const ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        lwe_input_indexes: *const ffi::c_void,
        bootstrapping_key: *const ffi::c_void,
        pbs_buffer: *mut i8,
        lwe_dimension: u32,
        glwe_dimension: u32,
        polynomial_size: u32,
        base_log: u32,
        level_count: u32,
        num_samples: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_programmable_bootstrap_amortized(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        pbs_buffer: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_programmable_bootstrap_32(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        buffer: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        level_count: u32,
        input_lwe_ciphertext_count: u32,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_programmable_bootstrap_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        buffer: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        level_count: u32,
        input_lwe_ciphertext_count: u32,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_programmable_bootstrap_lwe_ciphertext_vector_32(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_output_indexes: *const ffi::c_void,
        lut_vector: *const ffi::c_void,
        lut_vector_indexes: *const ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        lwe_input_indexes: *const ffi::c_void,
        bootstrapping_key: *const ffi::c_void,
        buffer: *mut i8,
        lwe_dimension: u32,
        glwe_dimension: u32,
        polynomial_size: u32,
        base_log: u32,
        level_count: u32,
        num_samples: u32,
        num_many_lut: u32,
        lut_stride: u32,
    );
}
unsafe extern "C" {
    pub fn cuda_programmable_bootstrap_lwe_ciphertext_vector_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_output_indexes: *const ffi::c_void,
        lut_vector: *const ffi::c_void,
        lut_vector_indexes: *const ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        lwe_input_indexes: *const ffi::c_void,
        bootstrapping_key: *const ffi::c_void,
        buffer: *mut i8,
        lwe_dimension: u32,
        glwe_dimension: u32,
        polynomial_size: u32,
        base_log: u32,
        level_count: u32,
        num_samples: u32,
        num_many_lut: u32,
        lut_stride: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_programmable_bootstrap(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        pbs_buffer: *mut *mut i8,
    );
}
unsafe extern "C" {
    pub fn has_support_to_cuda_programmable_bootstrap_cg_multi_bit(
        glwe_dimension: u32,
        polynomial_size: u32,
        level_count: u32,
        num_samples: u32,
    ) -> bool;
}
unsafe extern "C" {
    pub fn cuda_convert_lwe_multi_bit_programmable_bootstrap_key_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        dest: *mut ffi::c_void,
        src: *const ffi::c_void,
        input_lwe_dim: u32,
        glwe_dim: u32,
        level_count: u32,
        polynomial_size: u32,
        grouping_factor: u32,
    );
}
unsafe extern "C" {
    pub fn scratch_cuda_multi_bit_programmable_bootstrap_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        pbs_buffer: *mut *mut i8,
        glwe_dimension: u32,
        polynomial_size: u32,
        level_count: u32,
        input_lwe_ciphertext_count: u32,
        allocate_gpu_memory: bool,
    );
}
unsafe extern "C" {
    pub fn cuda_multi_bit_programmable_bootstrap_lwe_ciphertext_vector_64(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        lwe_array_out: *mut ffi::c_void,
        lwe_output_indexes: *const ffi::c_void,
        lut_vector: *const ffi::c_void,
        lut_vector_indexes: *const ffi::c_void,
        lwe_array_in: *const ffi::c_void,
        lwe_input_indexes: *const ffi::c_void,
        bootstrapping_key: *const ffi::c_void,
        buffer: *mut i8,
        lwe_dimension: u32,
        glwe_dimension: u32,
        polynomial_size: u32,
        grouping_factor: u32,
        base_log: u32,
        level_count: u32,
        num_samples: u32,
        num_many_lut: u32,
        lut_stride: u32,
    );
}
unsafe extern "C" {
    pub fn cleanup_cuda_multi_bit_programmable_bootstrap(
        stream: *mut ffi::c_void,
        gpu_index: u32,
        pbs_buffer: *mut *mut i8,
    );
}
