[backend.aws.cpu-big]
region = "eu-west-3"
image_id = "ami-0eda00173fe323828"
instance_type = "m6i.32xlarge"
user = "ubuntu"

[backend.aws.cpu-big_fallback]
region = "us-east-1"
image_id = "ami-0c6e54f3be8d03234"
instance_type = "m6i.32xlarge"
user = "ubuntu"

[backend.aws.cpu-small]
region = "eu-west-3"
image_id = "ami-0eda00173fe323828"
instance_type = "m6i.4xlarge"
user = "ubuntu"

[backend.aws.bench]
region = "eu-west-1"
image_id = "ami-0e99a601b5c4c7021"
instance_type = "hpc7a.96xlarge"
user = "ubuntu"

[backend.aws.bench-hpc8]
region = "eu-north-1"
image_id = "ami-0d7f32ee367bc2a69"
instance_type = "hpc8a.96xlarge"
user = "ubuntu"

# Profile used to build CUDA code without the need to get p-like instance.
[backend.aws.gpu-build]
region = "us-east-1"
image_id = "ami-0250f541bc1358116"
instance_type = "m6i.4xlarge"
user = "ubuntu"

[backend.aws.single-h100]
region = "us-east-1"
image_id = "ami-0250f541bc1358116"
instance_type = "p5.4xlarge"
user = "ubuntu"

[backend.aws.single-h100_1stfallback]
region = "us-east-2"
image_id = "ami-0c924a8e0a210a709"
instance_type = "p5.4xlarge"
user = "ubuntu"

[backend.aws.single-h100_2ndfallback]
region = "us-west-1"
image_id = "ami-0fe3273232bc2fb8a"
instance_type = "p5.4xlarge"
user = "ubuntu"

[backend.aws.single-h100_3rdfallback]
region = "us-west-2"
image_id = "ami-057682b0cfedeaf20"
instance_type = "p5.4xlarge"
user = "ubuntu"

[backend.aws.4-l40]
region = "us-east-1"
image_id = "ami-0250f541bc1358116"
instance_type = "g6.24xlarge"
user = "ubuntu"
fallbacks = [ "hyperstack.4-l40", "terraform.scaleway-4-l40" ]

[backend.aws.small-gpu]
region = "us-east-1"
image_id = "ami-0250f541bc1358116"
instance_type = "g6.2xlarge"
user = "ubuntu"

[backend.hyperstack.gpu-test]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R570 CUDA 12.8"
flavor_name = "n3-L40x1"
user = "ubuntu"
fallbacks = [ "terraform.scaleway-small-gpu", "hyperstack.rtx-a6000" ]

[backend.hyperstack.single-h100]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R570 CUDA 12.8"
flavor_name = "n3-H100x1"
user = "ubuntu"

[backend.hyperstack.2-h100]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R570 CUDA 12.8"
flavor_name = "n3-H100x2"
user = "ubuntu"

[backend.hyperstack.4-h100]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R570 CUDA 12.8"
flavor_name = "n3-H100x4"
user = "ubuntu"

[backend.hyperstack.multi-h100]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R570 CUDA 12.8"
flavor_name = "n3-H100x8"
user = "ubuntu"

[backend.hyperstack.multi-h100-nvlink]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R570 CUDA 12.8"
flavor_name = "n3-H100x8-NVLink"
user = "ubuntu"

[backend.hyperstack.multi-h100-sxm5]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R570 CUDA 12.8"
flavor_name = "n3-H100-SXM5x8"
user = "ubuntu"

[backend.hyperstack.multi-h100-sxm5_fallback]
environment_name = "us-1"
image_name = "Ubuntu Server 22.04 LTS R570 CUDA 12.8"
flavor_name = "n3-H100-SXM5x8"
user = "ubuntu"

[backend.hyperstack.multi-a100-nvlink]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R570 CUDA 12.8"
flavor_name = "n3-A100x8-NVLink"
user = "ubuntu"

[backend.hyperstack.l40]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R570 CUDA 12.8"
flavor_name = "n3-L40x1"
user = "ubuntu"

[backend.hyperstack.l40_fallback]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R570 CUDA 12.8"
flavor_name = "n3-RTX-A6000x1"
user = "ubuntu"

[backend.hyperstack.l40-tests]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R570 CUDA 12.8"
flavor_name = "n3-L40x1"
user = "ubuntu"
fallbacks = [ "hyperstack.rtx-a6000", "terraform.scaleway-small-gpu" ]

# Fallback target only.
[backend.hyperstack.rtx-a6000]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R570 CUDA 12.8"
flavor_name = "n3-RTX-A6000x1"
user = "ubuntu"

[backend.hyperstack.4-l40]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R570 CUDA 12.8"
flavor_name = "n3-L40x4"
user = "ubuntu"

[backend.hyperstack.4-l40_fallback]
environment_name = "norway"
image_name = "Ubuntu Server 22.04 LTS R570 CUDA 12.8"
flavor_name = "n3-RTX-A4000x4"
user = "ubuntu"

[backend.hyperstack.8-l40]
environment_name = "canada"
image_name = "Ubuntu Server 22.04 LTS R570 CUDA 12.8"
flavor_name = "n3-L40x8"
user = "ubuntu"

[backend.terraform.scaleway-multi-h100-sxm5]
script_path = "ci/terraform_scripts/scaleway/terraform.tf"
instance_type = "H100-SXM-8-80G"
user = "ubuntu"

[backend.terraform.scaleway-4-h100-sxm5]
script_path = "ci/terraform_scripts/scaleway/terraform.tf"
instance_type = "H100-SXM-4-80G"
user = "ubuntu"

[backend.terraform.scaleway-2-h100-sxm5]
script_path = "ci/terraform_scripts/scaleway/terraform.tf"
instance_type = "H100-SXM-2-80G"
user = "ubuntu"

[backend.terraform.scaleway-2-h100-sxm5-tests]
script_path = "ci/terraform_scripts/scaleway/terraform.tf"
instance_type = "H100-SXM-2-80G"
user = "ubuntu"
fallbacks = [
    "hyperstack.2-h100",
    "terraform.scaleway-4-h100-sxm5",
    "hyperstack.4-h100",
]

[backend.terraform.scaleway-single-h100]
script_path = "ci/terraform_scripts/scaleway/terraform.tf"
instance_type = "H100-1-80G"
user = "ubuntu"

[backend.terraform.scaleway-single-h100_fallback]
script_path = "ci/terraform_scripts/scaleway/terraform.tf"
instance_type = "H100-SXM-2-80G"
user = "ubuntu"

[backend.terraform.scaleway-single-h100-tests]
script_path = "ci/terraform_scripts/scaleway/terraform.tf"
instance_type = "H100-1-80G"
user = "ubuntu"
fallbacks = [
    "hyperstack.single-h100",
    "terraform.scaleway-2-h100-sxm5",
    "terraform.scaleway-4-h100-sxm5",
]

[backend.terraform.scaleway-4-l40]
script_path = "ci/terraform_scripts/scaleway/terraform.tf"
instance_type = "L40S-4-48G"
user = "ubuntu"

[backend.terraform.scaleway-2-l4]
script_path = "ci/terraform_scripts/scaleway/terraform.tf"
instance_type = "L4-2-24G"
user = "ubuntu"

[backend.terraform.scaleway-small-gpu]
script_path = "ci/terraform_scripts/scaleway/terraform.tf"
instance_type = "L40S-1-48G"
user = "ubuntu"
fallbacks = [ "hyperstack.gpu-test", "terraform.scaleway-2-l4" ]
