name: aws_tfhe_noise_checks

env:
  CARGO_TERM_COLOR: always
  ACTION_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  RUSTFLAGS: "-C target-cpu=native"
  RUST_BACKTRACE: "full"
  RUST_MIN_STACK: "8388608"
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  SLACK_ICON: https://pbs.twimg.com/profile_images/1274014582265298945/OjBKP9kn_400x400.png
  SLACK_USERNAME: ${{ secrets.BOT_USERNAME }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  SLACKIFY_MARKDOWN: true
  PULL_REQUEST_MD_LINK: ""
  CHECKOUT_TOKEN: ${{ secrets.REPO_CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}


on:
  # Allows you to run this workflow manually from the Actions tab as an alternative.
  workflow_dispatch:

permissions:
  contents: read

# zizmor: ignore[concurrency-limits] only Zama organization members can trigger this workflow

jobs:
  setup-instance:
    name: aws_tfhe_noise_checks/setup-instance
    uses: ./.github/workflows/slab_setup.yml
    with:
      backend: aws
      # We want an hpc7a more compute, will be faster
      profile: bench
    secrets:
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}

  noise-checks:
    name: aws_tfhe_noise_checks/noise-checks
    needs: setup-instance
    runs-on: ${{ needs.setup-instance.outputs.runner-name }}
    timeout-minutes: 1440
    steps:
      - name: Checkout tfhe-rs
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: 'false'
          token: ${{ env.CHECKOUT_TOKEN }}

      - name: Install latest stable
        uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # zizmor: ignore[stale-action-refs] this action doesn't create releases
        with:
          toolchain: stable

      - name: Run noise checks
        timeout-minutes: 1440
        run: |
          make test_noise_check

      - name: Set pull-request URL
        if: ${{ !success() }}
        run: |
          echo "PULL_REQUEST_MD_LINK=[pull-request](${PR_BASE_URL}${PR_NUMBER}), "  >> "${GITHUB_ENV}"
        env:
          PR_BASE_URL: ${{ vars.PR_BASE_URL }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Slack Notification
        if: ${{ !success() }}
        continue-on-error: true
        uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "Noise checks tests finished with status: ${{ job.status }}. (${{ env.PULL_REQUEST_MD_LINK }}[action run](${{ env.ACTION_RUN_URL }}))"

  teardown-instance:
    name: aws_tfhe_noise_checks/teardown-instance
    if: ${{ always() && needs.setup-instance.result != 'skipped' }}
    needs: [ setup-instance, noise-checks ]
    uses: ./.github/workflows/slab_teardown.yml
    with:
      runner-name: ${{ needs.setup-instance.outputs.runner-name }}
      notification-context: noise-checks
    secrets:
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
