# Run data related tests
name: aws_data_tests

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C target-cpu=native"
  RUST_BACKTRACE: "full"
  RUST_MIN_STACK: "8388608"
  CHECKOUT_TOKEN: ${{ secrets.REPO_CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}

on:
  # Allows you to run this workflow manually from the Actions tab as an alternative.
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

# zizmor: ignore[concurrency-limits] concurrency is managed after instance setup to ensure safe provisioning

jobs:
  data-tests:
    name: aws_data_tests/data-tests (bpr)
    if:
      (github.event_name == 'push' && github.repository == 'zama-ai/tfhe-rs') ||
      github.event_name != 'push'
    runs-on: "runs-on=${{ github.run_id }}/runner=cpu-small"
    concurrency:
      group: ${{ github.workflow_ref }}${{ github.ref == 'refs/heads/main' && github.sha || '' }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - name: Checkout tfhe-rs
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: "true" # Needed to pull lfs data
          token: ${{ env.CHECKOUT_TOKEN }}

      # Cache key is an aggregated hash of lfs files hashes
      - name: Get LFS data sha
        id: hash-lfs-data
        run: |
          SHA=$(git lfs ls-files -l -I utils/tfhe-backward-compat-data,tests/corrupted_inputs_deserialization | sha256sum | cut -d' ' -f1)
          echo "sha=${SHA}" >> "${GITHUB_OUTPUT}"

      - name: Retrieve data from cache
        id: retrieve-data-cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 #v6.1.0
        with:
          path: |
            utils/tfhe-backward-compat-data/**/*.cbor
            utils/tfhe-backward-compat-data/**/*.bcode
            tests/corrupted_inputs_deserialization/**/*.bcode
          key: ${{ steps.hash-lfs-data.outputs.sha }}

      - name: Pull test data
        if: steps.retrieve-data-cache.outputs.cache-hit != 'true'
        run: |
          make pull_backward_compat_data
          make pull_corrupted_inputs_data

      # Pull token was stored by action/checkout to be used by lfs, we don't need it anymore
      - name: Remove git credentials
        run:
          | # Starting version 6.0, action/checkout uses a dedicated file for git credentials
          git config --local --unset-all http.https://github.com/.extraheader || rm "${RUNNER_TEMP}"/git-credentials-*.config

      - name: Install latest stable
        uses: dtolnay/rust-toolchain@7e38f4b43b4db5c8dd498af069a4f6196df1d067 # zizmor: ignore[stale-action-refs] this action doesn't create releases
        with:
          toolchain: stable

      - name: Run backward compatibility tests
        run: |
          make test_backward_compatibility_ci

      - name: Run corrupted inputs deserialization tests
        run: |
          make test_corrupted_inputs_ci

      - name: Store data in cache
        if: steps.retrieve-data-cache.outputs.cache-hit != 'true'
        continue-on-error: true
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 #v6.1.0
        with:
          path: |
            utils/tfhe-backward-compat-data/**/*.cbor
            utils/tfhe-backward-compat-data/**/*.bcode
            tests/corrupted_inputs_deserialization/**/*.bcode
          key: ${{ steps.hash-lfs-data.outputs.sha }}

      - name: Slack Notification
        if: ${{ failure() || (cancelled() && github.event_name != 'pull_request') }}
        continue-on-error: true
        uses: ./.github/actions/slack_notify
        with:
          status: ${{ job.status }}
          message: "Backward compatibility tests finished with status: ${{ job.status }}."
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          slack-username: ${{ secrets.BOT_USERNAME }}
          pull-request-base-url: ${{ vars.PR_BASE_URL }}
