name: aws_tfhe_noise_checks

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C target-cpu=native"
  RUST_BACKTRACE: "full"
  RUST_MIN_STACK: "8388608"
  CHECKOUT_TOKEN: ${{ secrets.REPO_CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}

on:
  # Allows you to run this workflow manually from the Actions tab as an alternative.
  workflow_dispatch:

permissions:
  contents: read

# zizmor: ignore[concurrency-limits] only Zama organization members can trigger this workflow

jobs:
  setup-instance:
    name: aws_tfhe_noise_checks/setup-instance
    uses: ./.github/workflows/slab_setup.yml
    with:
      backend: aws
      # We want an hpc7a more compute, will be faster
      profile: bench
    secrets:
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}

  noise-checks:
    name: aws_tfhe_noise_checks/noise-checks
    needs: setup-instance
    runs-on: ${{ needs.setup-instance.outputs.runner-name }}
    timeout-minutes: 1440
    steps:
      - name: Checkout tfhe-rs
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: "false"
          token: ${{ env.CHECKOUT_TOKEN }}

      - name: Install latest stable
        uses: dtolnay/rust-toolchain@7e38f4b43b4db5c8dd498af069a4f6196df1d067 # zizmor: ignore[stale-action-refs] this action doesn't create releases
        with:
          toolchain: stable

      - name: Run noise checks
        timeout-minutes: 1440
        run: |
          make test_noise_check

      - name: Slack Notification
        if: ${{ !success() }}
        continue-on-error: true
        uses: ./.github/actions/slack_notify
        with:
          status: ${{ job.status }}
          message: "Noise checks tests finished with status: ${{ job.status }}."
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          slack-username: ${{ secrets.BOT_USERNAME }}
          pull-request-base-url: ${{ vars.PR_BASE_URL }}

  teardown-instance:
    name: aws_tfhe_noise_checks/teardown-instance
    if: ${{ always() && needs.setup-instance.outputs.runner-name != '' }}
    needs: [setup-instance, noise-checks]
    uses: ./.github/workflows/slab_teardown.yml
    with:
      runner-name: ${{ needs.setup-instance.outputs.runner-name }}
      notification-context: noise-checks
    secrets:
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
