# Run all benchmarks displayed in the internal documentation.
name: benchmark_summary

run-name: Benchmark Summary

on:
  workflow_dispatch:
    inputs:
      run-cpu-benchmarks:
        description: "Run CPU benchmarks"
        type: boolean
        default: true
      run-gpu-benchmarks:
        description: "Run GPU benchmarks"
        type: boolean
        default: true
      gpu-profile:
        description: "GPU Instance type"
        required: true
        default: "hyperstack::multi-h100-sxm5 (n3-H100-SXM5x8)"
        type: choice
        options:
          - "hyperstack::l40 (n3-L40x1)"
          - "hyperstack::4-l40 (n3-L40x4)"
          - "hyperstack::multi-a100-nvlink (n3-A100x8-NVLink)"
          - "hyperstack::single-h100 (n3-H100x1)"
          - "hyperstack::2-h100 (n3-H100x2)"
          - "hyperstack::4-h100 (n3-H100x4)"
          - "hyperstack::multi-h100 (n3-H100x8)"
          - "hyperstack::multi-h100-nvlink (n3-H100x8-NVLink)"
          - "hyperstack::multi-h100-sxm5 (n3-H100-SXM5x8)"
          - "scaleway::multi-h100-sxm5 (H100-SXM-8-80G)"
      bench_type:
        description: "Benchmarks type"
        type: choice
        default: both
        options:
          - latency
          - throughput
          - both
      run-hpu-benchmarks:
        description: "Run HPU benchmarks"
        type: boolean
        default: true


permissions: {}

# zizmor: ignore[concurrency-limits] only Zama organization members can trigger this workflow

jobs:
  parse-gpu-inputs:
    name: benchmark_summary/parse-gpu-inputs
    if: inputs.run-gpu-benchmarks
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.parse_profile.outputs.backend }}
      profile: ${{ steps.parse_profile.outputs.profile }}
      hardware_name: ${{ steps.parse_profile.outputs.hardware }}
    steps:
      - name: Checkout tfhe-rs repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: 'false'
          token: ${{ secrets.REPO_CHECKOUT_TOKEN }}

      - name: Parse profile and hardware name
        id: parse_profile
        env:
          INPUTS_PROFILE: ${{ inputs.gpu-profile }}
        run: python3 ci/parse_gpu_benchmark_profile.py "$INPUTS_PROFILE" "$GITHUB_OUTPUT"

  run-benchmarks-cpu:
    name: benchmark_documentation/run-benchmarks-cpu-integer
    uses: ./.github/workflows/benchmark_cpu_common.yml
    if: inputs.run-cpu-benchmarks
    with:
      command: summary
      bench_type: ${{ inputs.bench_type }}
      params_type: classical + multi_bit
    secrets:
      BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      REPO_CHECKOUT_TOKEN: ${{ secrets.REPO_CHECKOUT_TOKEN }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_URL: ${{ secrets.SLAB_URL }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}

  run-benchmarks-gpu:
    name: benchmark_documentation/run-benchmarks-gpu
    uses: ./.github/workflows/benchmark_gpu_common.yml
    if: inputs.run-gpu-benchmarks
    needs: parse-gpu-inputs
    with:
      backend: ${{ needs.parse-gpu-inputs.outputs.backend }}
      profile: ${{ needs.parse-gpu-inputs.outputs.profile }}
      hardware_name: ${{ needs.parse-gpu-inputs.outputs.hardware_name }}
      command: summary
      bench_type: ${{ inputs.bench_type }}
      params_type: classical + multi_bit
    secrets:
      BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      REPO_CHECKOUT_TOKEN: ${{ secrets.REPO_CHECKOUT_TOKEN }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_URL: ${{ secrets.SLAB_URL }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}

# TODO add make recipe for HPU benchmarks
#  run-benchmarks-hpu:
#    name: benchmark_documentation/run-benchmarks-hpu
#    uses: ./.github/workflows/benchmark_hpu_common.yml
#    if: inputs.run-hpu-benchmarks
#    with:
#      command: summary
#      bench_type: ${{ inputs.bench_type }}
#      v80_pcie_dev: 24
#      v80_serial_number: XFL12NWY3ZKG
#    secrets:
#      BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
#      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
#      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#      REPO_CHECKOUT_TOKEN: ${{ secrets.REPO_CHECKOUT_TOKEN }}
#      JOB_SECRET: ${{ secrets.JOB_SECRET }}
#      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
#      SLAB_URL: ${{ secrets.SLAB_URL }}
#      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
#      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
